<template>
  <v-list
    dense
    nav
    rounded
  >

    <v-list-group
      prepend-icon="markunread_mailbox"
    >
      <template v-slot:activator>
        <v-list-item-content>
          <v-list-item-title>
            页面
          </v-list-item-title>
        </v-list-item-content>
      </template>
      <v-list-item
        nuxt
        link
        dense
        to="/s"
      >
        <v-list-item-title>杂七杂八</v-list-item-title>
        <v-list-item-action>
          <v-chip
            class="ma-2"
            color="pink"
            label
            text-color="white"
            small
          >
            0
          </v-chip>
        </v-list-item-action>
      </v-list-item>
    </v-list-group>
  </v-list>
</template>
